### ISSUE TITLE
页面白屏问题

### ISSUE THREAD

**Issue by xiaojingming** [tencentyun/h5-panel-template#11]
在本地调式工具中页面有显示，但是在微信小程序中页面显示白屏，通过微信开发者模式发现app节点下的内容为空且无任何报错
```
App.vue
<template>
  <router-view />
  <layout />
</template>
```
其中layout为自定义组件，如果把layout组件去掉，则页面显示正常，请问是为什么呢

**Comment by imgss** [comment]
> 但是在微信小程序中页面显示白屏

这个是指打包上传后,通过小程序预览面板,发现白屏吗
最好能提供一个可以复现的demo,方便定位问题

**Comment by xiaojingming** [comment]
> 

是的，在小程序中显示白屏
https://github.com/xiaojingming/demo.git 这个是简化的demo地址
把layout组件中的van-icon去掉就可以显示

**Comment by imgss** [comment]
我跑了一下,带van-icon也是正常的吧
![2831658134531_ pic](https://user-images.githubusercontent.com/20496797/179477424-c462f152-e279-4838-8187-a7ecc9f0784d.jpg)

**Comment by xiaojingming** [comment]
> 

确实是可以的😂，我按照自己的项目逻辑改了一下（代码已经上传了），还是在layout组件中，如果使用Test组件，页面还是会白屏

**Comment by xiaojingming** [comment]
@imgss 谢谢，😂不知道是不是兼容的问题，我在其它手机上面是可以的，但是在iphone6s上确实是会白屏

**Comment by imgss** [comment]
6s是7年前的手机了，有可能编译的时候，有些新的语法没有被转化，结果6s不支持了
