### ISSUE TITLE
H5 自定义设备详情视图的问题

### ISSUE THREAD

**Issue by xiaojingming** [tencentyun/h5-panel-template#13]
请问通过sdk.showDeviceDetail()显示设备详情页，可以将设备详情页面提供的删除设备按钮替换或者添加函数进行监听吗
![5c3cd30651bd5416b405076ec99bd65](https://user-images.githubusercontent.com/52662662/180715774-06859586-bca8-4773-ae5e-0a34425a04e7.jpg)

**Comment by imgss** [comment]
支持通过`extendButtons`新增自定义按钮和添加事件，参考 https://cloud.tencent.com/document/product/1081/67443#.E8.AE.BE.E5.A4.87.E8.AF.A6.E6.83.85

**Comment by xiaojingming** [comment]
@imgss 请问可以覆盖原本的删除设备按钮吗，或者往删除设备按钮上添加逻辑

**Comment by imgss** [comment]
具体什么场景需要覆盖呢，添加逻辑可以的：
```js
document.querySelector('.explorer-h5-device-detail .explorer-btn').addEventListener('click', () => {})
```

**Comment by xiaojingming** [comment]
现在是想在删除的时候去通知网关删除的操作

**Comment by imgss** [comment]
https://cloud.tencent.com/document/product/1081/47441#.E6.8B.93.E6.89.91.E5.85.B3.E7.B3.BB.E5.8F.98.E5.8C.96
子设备被删除，网关设备应该能收到 mqtt 消息，不需要前端通知

**Comment by xiaojingming** [comment]
@imgss 谢谢，刚刚问了一下设备的同学。还有一个问题想问一下您，如果使用上面的事件监听，会获取不到这个元素导致报错，要在什么时机去添加这样的一个监听呢

**Comment by imgss** [comment]
调用完`sdk.showDeviceDetail()`再监听， 
```js
sdk. showDeviceDetai().then(() => { // 监听事件 })
```

**Comment by xiaojingming** [comment]
@imgss 十分感谢！😉
